# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs

jobs:

  execute-pretier:
    docker:
      - image: miyajan/prettier:1.15.3
    steps:
      - checkout
      - run:
          name: Run Prettier
          - run: npm run format

  run-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.23.1-focal
    # Steps to the job
    steps:
      - checkout
      - run: npm i -D @playwright/test
      - run: npx playwright install --with-deps
      - run:
          name: Run test
          command: PLAYWRIGHT_JUNIT_OUTPUT_NAME=results.xml npx playwright test --reporter=junit
      - store_test_results:
          path: results.xml
# Invoke jobs via workflows
workflows:
  run-test-workflow:
    jobs:
      - run-test
